# Copyright 2020 Wayback Archiver. All rights reserved.
# Use of this source code is governed by the GNU GPL v3
# license that can be found in the LICENSE file.
#
name: Dispatch

on:
  release:
    types: [published]

permissions: {}

jobs:
  release-brew:
    if: github.repository == 'wabarc/wayback'
    name: Repository Dispatch
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34 # v1.5.0
        with:
          egress-policy: block
          disable-telemetry: true
          allowed-endpoints: >
            github.com:443
            api.github.com:443

      - name: Dispatch repository in wabarc/aur
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3.0.0
        with:
          repository: wabarc/homebrew-wayback
          event-type: publish
          token: ${{ secrets.PAT_WORKFLOW }}
          client-payload: '{"from": "${{ github.repository }}", "channel": "stable"}'
